default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dannykulas
  password: 
  host: localhost

development:
  <<: *default
  database: fishdetroit_dev

test:
  <<: *default
  database: fishdetroit_test

production:
  <<: *default
  database: fishdetroit_prod
  username: dannykulas
  password: 
